### ISSUE TITLE
Problem with server-columns and server-name Configuration

### ISSUE THREAD

**Issue by Synt3x** [Dantevg/WebStats#106]
# Description
I'm experiencing issues with the server-columns and server-name settings in my WebStats configuration. Despite proper configuration, the server row is not displaying correctly.
# Current Configuration
```YAML

# These columns will not be displayed on individual player's rows, but on a
# separate 'Server' row.
server-columns: [TPS,Online Players, Uptime]

# When displaying the server row defined above, use this name instead of "Server".
# You can use PlaceholderAPI placeholders here.
server-name: "%server_name% (%server_version%)"

# Relevant placeholders configuration
placeholders:
  %server_tps%: TPS
  %server_online%: Online Players
  %server_uptime%: Uptime
```
# What I've Tried
* I've confirmed my PlaceholderAPI placeholders are working correctly (verified with /papi parse me %server_tps%)
* I've tried different formatting for the server-columns setting (both array notation and list format)
* I've tried changing the server-name value
* I've restarted the server after each configuration change

# Expected Behavior
A server row should appear in my stats table with:
* The name specified in server-name instead of "Server"
* Only showing the columns specified in server-columns (TPS, Online Players, Uptime)

# Actual Behavior
The server row is not displaying properly or not showing at all.

# Environment
* WebStats version: WebStats-1.11.0+mc1.18+.jar
* Server type/version: paper-1.21.5-22.jar
* PlaceholderAPI version: PlaceholderAPI-2.11.6.jar

# Additional Information:
The placeholders for server data are working correctly when tested with /papi parse me %server_tps%, but they don't appear in the WebStats display.

I really appreciate any help with resolving this issue. Thank you for creating such a useful plugin - it's been a great addition to my server, and I'm looking forward to getting this feature working properly!

**Comment by Dantevg** [comment]
Hi, thanks for the extensive issue!

The placeholders should be wrapped in quotes like so: (otherwise the yaml parser can't handle it)
```yaml
placeholders:
  '%server_tps%': TPS
  '%server_online%': Online Players
  '%server_uptime%': Uptime
```
Then it should work properly.

I now notice that the "Player" column is duplicated if you set a custom `server-name`, will fix that now.

**Comment by Synt3x** [comment]
I think that I use quotations, but missed it in my example. I will test the latest change you did and come back.

**Comment by Synt3x** [comment]
@Dantevg I have tried the latest build from you, but I can't seem to get it to work. Do you mind looking at my configuration file?

```
# Configuration file for WebStats
# See https://github.com/Dantevg/WebStats/wiki/Config-file for more info

# Port to use for the web server. Make sure that this port corresponds
# to the one set in the web page js script.
port: 8905

# A list of tables to show on the webpage. Default is to show a single unnamed
# table which contains all columns, sorted by player name in ascending order.
tables:
  - # The name of the table. This will be displayed above it on the webpage.
    # Leave empty for no title / name.
    name: Playerdata

    # Only these columns will appear, in the order specified.
    # When commented out, all columns will be displayed, in alphabetical order (default).
    # The 'Player' column will always be displayed, as the first column.
    columns: [Play Time,Level,Time slept,Deaths,Walked,Sprinted,Flying,Crouch walked,Jumped, Swimed,Horse rided,Mobs killed,Diamonds mined,Netherite Ore,Fish caught,Animals bred,Villager traded]

    # Which column to sort by
    sort-column: Player

    # Whether to sort ascending (smallest first) or descending (largest first)
    sort-direction: ascending

# These columns will not be displayed on individual player's rows, but on a
# separate 'Server' row.
server-columns: [TPS,Online Players, Uptime]
# When displaying the server row defined above, use this name instead of "Server".
# You can use PlaceholderAPI placeholders here. (uncomment to use)
server-name: "Serverdata"

# Specify the unit in which data from a column is *stored*. WebStats will use
# this information to automatically adjust the *displayed* units.
# Units you can use here:
# - time (duration, not wall clock time): milliseconds/ms, ticks, seconds/s, minutes/min, hours/h, days/d
# - distance: blocks/metres/meters/m, kilometres/kilometers/km
# - date: formatted date, timestamp
# - item count: items, items16 (for 16-stackables)
column-units:
#  Column Name: source unit
  Play Time: 
  Level:
  Deaths: 
  Mobs killed:
  Fish caught: items64
  Time slept: 
  Villager traded:
  Animals bred:
  Diamonds mined: items64
  Netherite Ore: items64
  Jumped:
  Walked: cm
  Swimed: cm
  Crouch walked: cm
  Horse rided: cm
  Sprinted: cm
  Flying: cm
  
# HTTPS configuration. Uncomment to enable HTTPS.
# See https://github.com/Dantevg/WebStats/wiki/HTTPS for how to set up.
#https:
#  # The path to the keystore file, relative to the plugin config folder.
#  keystore-file: webstats.p12
#  # The password of the keystore file.
#  keystore-password: ""

# Whether to store IP to player name mapping in 'ip-to-names.yml',
# used for matching your IP to your player name
store-player-ips: true

# Whether to keep old statistics in stats.csv when executing '/webstats export'.
# Disabling this will override older saved statistics in stats.csv when exporting.
export-cumulative: true

# The interval in which to export all stats to stats.csv, in minutes.
# Set to 0 to disable (default).
export-interval: 1

# Whether to also serve the web page from within the plugin. (not only the stats)
# Disable this when you want to use your own external web server, enable this
# when you do not have one.
serve-webpage: true

# A list of additional files to serve (index.html, WebStats-dist.js etc. are
# implicitly part of this list). For this list to have effect, `serve-webpage`
# must be enabled in the config. Paths are relative to `plugins/WebStats/web/`.
additional-resources: []

# When serve-webpage is enabled, this is the tab title of the webpage.
webpage-title: "Minecraft Stats"

# Scoreboard objectives to use. When '*' is present, uses all objectives.
# (make sure to enclose the '*' in quotes)
# You can also give a custom name for an objective by writing the new name
# after the original name, separated by a colon.
#objectives:
#  - '*'
#  - Objective Name
#  - Objective Name: Custom Name

# Database credentials for MySQL database connectivity and placeholder storage
#database:
#  hostname: localhost
#  username: DATABASE USERNAME
#  password: DATABASE PASSWORD
#  config: # uncomment from here to use MySQL database connectivity
#    - database: DATABASE NAME
#      table: TABLE NAME
#      convert: # Some examples, refer to documentation for explanations
#        - [rename, from-column, to-column]
#        - [json, column]
#        - [key-value, key-column, value-column]
#        - [uuid, column]

# Configuration for the PlaceholderAPI connectivity (uncomment to use)
# If you want to use a `.`, you need to replace it by `[dot]`
placeholders:
  '%server_tps%': TPS
  '%server_online%': Online Players
  '%server_uptime%': Uptime
  '%statistic_time_played%': Play Time
  '%player_level%': Level
  '%statistic_deaths%': Deaths
  '%statistic_mob_kills%': Mobs killed
  '%statistic_fish_caught%': Fish caught
  '%statistic_sleep_in_bed%': Time slept
  '%statistic_traded_with_villager%': Villager traded
  '%statistic_animals_bred%': Animals bred
  '%statistic_mine_block:deepslate_diamond_ore,diamond_ore%': Diamonds mined
  '%statistic_mine_block:ancient_debris%': Netherite Ore
  '%statistic_sprint_one_cm%': Sprinted
  '%statistic_aviate_one_cm%': Flying
  '%statistic_jump%': Jumped
  '%statistic_walk_one_cm%': Walked
  '%statistic_swim_one_cm%': Swimed
  '%statistic_crouch_one_cm%': Crouch walked
  '%statistic_horse_one_cm%': Horse rided

# Set to true to store placeholders in a file, for when players go offline. (uncomment to use)
# Mutually exclusive with `store-placeholders-database`
store-placeholders-in-file: true

# Alternatively, the database name to store placeholders in. (uncomment to use)
# Make sure to specify the database hostname, username and password above
# Mutually exclusive with `store-placeholders-in-file`
#store-placeholders-database: WebStats_placeholders

# Placeholder values to consider "empty". By default, only empty strings and
# the placeholder name itself are considered empty. Some placeholders return
# other values for "empty", like "0". You can add those here. (uncomment to use)
#placeholder-empty-values:
#  '%placeholder_name%': 0
#
# Configuration for the Discord webhook function (uncomment to use)
# Make sure to set the webhook URL
#discord-webhook:
#  # The webhook URL. Get this from Discord
#  url: ""
#  
#  # The update interval, in minutes
#  update-interval: 5
#  
#  # Show the top n rows/players
#  display-count: 10
#  
#  # Message title, text to be displayed before the embeds
#  title:
#  
#  # Disable if you want to set your own icon and name in Discord's settings.
#  # When enabled, WebStats will provide its own name and icon for the webhook.
#  override-icon-and-name: true
#  
#  # Each item in this list is one embed
#  embeds:
#    - # The title of the embed. Leave empty for no title
#      title:
#      
#      # Which column to sort by
#      sort-column: Player
#      
#      # Whether to sort ascending (smallest first) or descending (largest first)
#      sort-direction: ascending
#      
#      # Which columns to display. Defaults to using the columns defined at the
#      # top of this file in a single embed, or all columns otherwise.
#      # Note that Discord displays max 3 columns next to each other (including
#      # the "Player" column which is always present)
#      columns: [Deaths]
#      
#      # A further example
#    - title: Best miners
#      sort-column: Mine All Diamond
#      sort-direction: ascending
#      columns: [Mine All Diamond, Mine Ancient Debris]

# Whether to save placeholders before any plugins are disabled on server shutdown
# This is a fix for error "java.lang.IllegalStateException: zip file closed."
# You can leave this off if you don't experience this error.
save-placeholders-on-plugin-disable: false

```

**Comment by Dantevg** [comment]
It looks like you want the server statistics in a separate table from the player statistics. You've selected all the player columns in the "Playerdata" table, but you haven't created a second table for the server's statistics, so the columns TPS, Online Players and Uptime won't be displayed at all.

The server is handled just like another player, so the server's stats are handled just like the player stats. You'll need to add a second table entry and select the server columns there as well.

**Comment by Dantevg** [comment]
@Synt3x did you manage to get it working with this?

**Comment by Synt3x** [comment]
Haven't had the time, will update the ticket this weekend and then close it.

**Comment by Dantevg** [comment]
Alright no problem! Don't rush, I was just wondering.

**Comment by Synt3x** [comment]
Hello @Dantevg 

Coulnd't get it to work, do you mind sharing an example how to implement player data and server data?

**Comment by Dantevg** [comment]
You only need to add the following to the `tables` config:
```yml
  - name: Serverdata
    columns: [TPS, Online Players, Uptime]
```

<details><summary>This is what the config.yml you posted earlier then looks like</summary>
<p>

```yml
# Configuration file for WebStats
# See https://github.com/Dantevg/WebStats/wiki/Config-file for more info

# Port to use for the web server. Make sure that this port corresponds
# to the one set in the web page js script.
port: 8905

# A list of tables to show on the webpage. Default is to show a single unnamed
# table which contains all columns, sorted by player name in ascending order.
tables:
  - # The name of the table. This will be displayed above it on the webpage.
    # Leave empty for no title / name.
    name: Playerdata

    # Only these columns will appear, in the order specified.
    # When commented out, all columns will be displayed, in alphabetical order (default).
    # The 'Player' column will always be displayed, as the first column.
    columns: [Play Time,Level,Time slept,Deaths,Walked,Sprinted,Flying,Crouch walked,Jumped, Swimed,Horse rided,Mobs killed,Diamonds mined,Netherite Ore,Fish caught,Animals bred,Villager traded]

    # Which column to sort by
    sort-column: Player

    # Whether to sort ascending (smallest first) or descending (largest first)
    sort-direction: ascending

  - name: Server data
    columns: [TPS, Online Players, Uptime]

# These columns will not be displayed on individual player's rows, but on a
# separate 'Server' row.
server-columns: [TPS,Online Players, Uptime]
# When displaying the server row defined above, use this name instead of "Server".
# You can use PlaceholderAPI placeholders here. (uncomment to use)
server-name: "Serverdata"

# Specify the unit in which data from a column is *stored*. WebStats will use
# this information to automatically adjust the *displayed* units.
# Units you can use here:
# - time (duration, not wall clock time): milliseconds/ms, ticks, seconds/s, minutes/min, hours/h, days/d
# - distance: blocks/metres/meters/m, kilometres/kilometers/km
# - date: formatted date, timestamp
# - item count: items, items16 (for 16-stackables)
column-units:
#  Column Name: source unit
  Play Time: 
  Level:
  Deaths: 
  Mobs killed:
  Fish caught: items64
  Time slept: 
  Villager traded:
  Animals bred:
  Diamonds mined: items64
  Netherite Ore: items64
  Jumped:
  Walked: cm
  Swimed: cm
  Crouch walked: cm
  Horse rided: cm
  Sprinted: cm
  Flying: cm
  
# HTTPS configuration. Uncomment to enable HTTPS.
# See https://github.com/Dantevg/WebStats/wiki/HTTPS for how to set up.
#https:
#  # The path to the keystore file, relative to the plugin config folder.
#  keystore-file: webstats.p12
#  # The password of the keystore file.
#  keystore-password: ""

# Whether to store IP to player name mapping in 'ip-to-names.yml',
# used for matching your IP to your player name
store-player-ips: true

# Whether to keep old statistics in stats.csv when executing '/webstats export'.
# Disabling this will override older saved statistics in stats.csv when exporting.
export-cumulative: true

# The interval in which to export all stats to stats.csv, in minutes.
# Set to 0 to disable (default).
export-interval: 1

# Whether to also serve the web page from within the plugin. (not only the stats)
# Disable this when you want to use your own external web server, enable this
# when you do not have one.
serve-webpage: true

# A list of additional files to serve (index.html, WebStats-dist.js etc. are
# implicitly part of this list). For this list to have effect, `serve-webpage`
# must be enabled in the config. Paths are relative to `plugins/WebStats/web/`.
additional-resources: []

# When serve-webpage is enabled, this is the tab title of the webpage.
webpage-title: "Minecraft Stats"

# Scoreboard objectives to use. When '*' is present, uses all objectives.
# (make sure to enclose the '*' in quotes)
# You can also give a custom name for an objective by writing the new name
# after the original name, separated by a colon.
#objectives:
#  - '*'
#  - Objective Name
#  - Objective Name: Custom Name

# Database credentials for MySQL database connectivity and placeholder storage
#database:
#  hostname: localhost
#  username: DATABASE USERNAME
#  password: DATABASE PASSWORD
#  config: # uncomment from here to use MySQL database connectivity
#    - database: DATABASE NAME
#      table: TABLE NAME
#      convert: # Some examples, refer to documentation for explanations
#        - [rename, from-column, to-column]
#        - [json, column]
#        - [key-value, key-column, value-column]
#        - [uuid, column]

# Configuration for the PlaceholderAPI connectivity (uncomment to use)
# If you want to use a `.`, you need to replace it by `[dot]`
placeholders:
  '%server_tps%': TPS
  '%server_online%': Online Players
  '%server_uptime%': Uptime
  '%statistic_time_played%': Play Time
  '%player_level%': Level
  '%statistic_deaths%': Deaths
  '%statistic_mob_kills%': Mobs killed
  '%statistic_fish_caught%': Fish caught
  '%statistic_sleep_in_bed%': Time slept
  '%statistic_traded_with_villager%': Villager traded
  '%statistic_animals_bred%': Animals bred
  '%statistic_mine_block:deepslate_diamond_ore,diamond_ore%': Diamonds mined
  '%statistic_mine_block:ancient_debris%': Netherite Ore
  '%statistic_sprint_one_cm%': Sprinted
  '%statistic_aviate_one_cm%': Flying
  '%statistic_jump%': Jumped
  '%statistic_walk_one_cm%': Walked
  '%statistic_swim_one_cm%': Swimed
  '%statistic_crouch_one_cm%': Crouch walked
  '%statistic_horse_one_cm%': Horse rided

# Set to true to store placeholders in a file, for when players go offline. (uncomment to use)
# Mutually exclusive with `store-placeholders-database`
store-placeholders-in-file: true

# Alternatively, the database name to store placeholders in. (uncomment to use)
# Make sure to specify the database hostname, username and password above
# Mutually exclusive with `store-placeholders-in-file`
#store-placeholders-database: WebStats_placeholders

# Placeholder values to consider "empty". By default, only empty strings and
# the placeholder name itself are considered empty. Some placeholders return
# other values for "empty", like "0". You can add those here. (uncomment to use)
#placeholder-empty-values:
#  '%placeholder_name%': 0
#
# Configuration for the Discord webhook function (uncomment to use)
# Make sure to set the webhook URL
#discord-webhook:
#  # The webhook URL. Get this from Discord
#  url: ""
#  
#  # The update interval, in minutes
#  update-interval: 5
#  
#  # Show the top n rows/players
#  display-count: 10
#  
#  # Message title, text to be displayed before the embeds
#  title:
#  
#  # Disable if you want to set your own icon and name in Discord's settings.
#  # When enabled, WebStats will provide its own name and icon for the webhook.
#  override-icon-and-name: true
#  
#  # Each item in this list is one embed
#  embeds:
#    - # The title of the embed. Leave empty for no title
#      title:
#      
#      # Which column to sort by
#      sort-column: Player
#      
#      # Whether to sort ascending (smallest first) or descending (largest first)
#      sort-direction: ascending
#      
#      # Which columns to display. Defaults to using the columns defined at the
#      # top of this file in a single embed, or all columns otherwise.
#      # Note that Discord displays max 3 columns next to each other (including
#      # the "Player" column which is always present)
#      columns: [Deaths]
#      
#      # A further example
#    - title: Best miners
#      sort-column: Mine All Diamond
#      sort-direction: ascending
#      columns: [Mine All Diamond, Mine Ancient Debris]

# Whether to save placeholders before any plugins are disabled on server shutdown
# This is a fix for error "java.lang.IllegalStateException: zip file closed."
# You can leave this off if you don't experience this error.
save-placeholders-on-plugin-disable: false
```

</p>
</details>
