### ISSUE TITLE
Data/Players not showing up on webpage

### ISSUE THREAD

**Issue by CarterKJ** [Dantevg/WebStats#108]
To simplify debugging this, I'm using the default config/web demo. The plugin connects to the server just fine, but the webpage is blank. 

![Image](https://github.com/user-attachments/assets/d695b21a-3d46-49e8-8d2f-7ddfd029d2bc)

This is the json that is getting sent back, it sees the players, but it is not displaying on the website.
```
{
    "online": {
        "overzync": true,
        "Terraformy": true,
        "Pantouflard457": true
    },
    "scoreboard": {
        "entries": [],
        "columns": [],
        "scores": {}
    },
    "playernames": [],
    "units": {}
}
```

I am running paper 1.21.4 (build 229). If you need any more information, please let me know.

**Comment by CarterKJ** [comment]
Hello, I am using the default config for the data

(Currently using)
```
tables:
  - # The name of the table. This will be displayed above it on the webpage.
    # Leave empty for no title / name.
    name:

    # Only these columns will appear, in the order specified.
    # When commented out, all columns will be displayed, in alphabetical order (default).
    # The 'Player' column will always be displayed, as the first column.
    # columns: []

    # Which column to sort by
    #sort-column: Player

    # Whether to sort ascending (smallest first) or descending (largest first)
    #sort-direction: ascending
```
Right now, I just want to see the players' names. Even if I use PlaceholderAPI (for display name), there is still no data on the website

(Ive also tried this)
```
tables:
  - # The name of the table. This will be displayed above it on the webpage.
    # Leave empty for no title / name.
    name:

    # Only these columns will appear, in the order specified.
    # When commented out, all columns will be displayed, in alphabetical order (default).
    # The 'Player' column will always be displayed, as the first column.
    columns: [displayed name]

    # Which column to sort by
    #sort-column: Player

    # Whether to sort ascending (smallest first) or descending (largest first)
    #sort-direction: ascending
```
```
placeholders:
 '%placeholder_name%': displayed name
```
Neither has worked
