### ISSUE TITLE
Column number units

### ISSUE THREAD

**Issue by Dantevg** [Dantevg/WebStats#58]
Some values have large numbers and it can be hard to see what they mean. The option to specify per column what the unit of the values is would solve this. Possible units / categories:
- **time**: milliseconds, ticks(?), seconds, minutes, hours (e.g. `12:34:56.789`)
- **item count**: stacks, items (note: can be confusing for 16-stackables) (e.g. `1st 23`)
- **distance**: meters/blocks, kilometres (e.g. `123m`, `12.34km`)
- **date**: formatted, timestamp (regional formatting or ISO)
- ... more?

Example config: (`minutes`, `ticks`, `items`, `timestamp` are taken as the source units, WebStats will choose best units to display)
```yaml
column-units:
  Play Minutes: minutes
  Aviate: ticks
  Mine Diamond: items
  Last Seen: timestamp
```

Possible extra function: show original value on hover ("tooltip")
